version: '3' # version is the docker compose file format

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.7-slim
    image: aatkinson/flask-app:1.0
    environment:
      - FLASK_ENV=development
    ports:
      - 80:5000
