version: '3' # version is the docker compose file format

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.7-slim
    image: aatkinson/flask-app:1.0
    env_file:
      - .env.txt
    ports:
      - 80:5000
    networks:
      - mynet
    volumes:
      - mydata:/data

networks:
  mynet:

volumes:
  mydata:
